---
title: Images à chargement lent
hero_image: images/banner.png
description: Images à chargement lent
version: 4
listed: false
copyedit: false
last_tested: "2022 05 19"
steps:
  - title: Images à chargement lent
